version: '2.4'
services:
  hello-edge:
    image: hello-edge
    mem_limit: 200mb
    restart: always
    networks:
      - reverse-proxy
    volumes:
      - './publish/:/publish/'
      - './cfg-data/:/cfg-data/'
networks:
  reverse-proxy:
    name: reverse-proxy