version: '2.4'
services:
  hello-edge:
    image: hello-edge
    mem_limit: 200mb
    restart: always
    networks:
      - proxy-redirect
    volumes:
      - './publish/:/publish/'
      - './cfg-data/:/cfg-data/'
networks:
 proxy-redirect:
    external: true
    name: proxy-redirect